[tool.poetry]
name = "LinzNetz Data Analyzer"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.75.0"
uvicorn = "^0.17.6"
requests = "^2.27.1"
aiofiles = "^22.1.0"
matplotlib = "^3.6.0"
python-multipart = "^0.0.5"
pandas = "^1.5.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
flake8-comprehensions = "^3.8.0"
flake8-functions-names = "^0.3.0"
flake8-simplify = "^0.19.2"
pep8-naming = "^0.12.1"
flake8-use-fstring = "^1.3"
mypy = "^0.942"
pytest = "^7.1.1"
pylint = "^2.13.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
files = ["data_analyzer", "tests"]
python_version = "3.9"
warn_unreachable = true
warn_return_any = true
disallow_untyped_defs = true
show_error_codes = true
ignore_missing_imports = true
plugins = ["pydantic.mypy"]
exclude = [".git/", ".venv/", "__pycache__"]

[[tool.mypy.overrides]]
module = "tests.*"
strict_optional = false

[[tool.mypy.overrides]]
module = "some.autogenerated.files.*"
ignore_errors = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
addopts = "-Wall -Werror"
