name: Docker Dev Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
     postgres:
       image: postgres:12.5
       env:
         POSTGRES_DB: dataanalyzer
         POSTGRES_USER: dev
         POSTGRES_PASSWORD: dev
       ports:
         # Maps tcp port 5432 on service container to the host
         - 5432:5432
       # Set health checks to wait until postgres has started
       options: >-
         --health-cmd pg_isready
         --health-interval 10s
         --health-timeout 5s
         --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build dev
    - name: Run the Docker image
      run: docker-compose run dev --env POSTGRES_SERVER=localhost
        

