name: Docker Dev Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build dev
    - name: run database server
      run: docker-compose up -f docker/local-dev/docker-compose.yml -d
    - name: Run the Docker image
      run: docker-compose run dev
    - name: shut down database server
      run: docker-compose down -f docker/local-dev/docker-compose.yml
