name: Docker App Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libpq-dev dependency
      run: |
        sudo apt-get install -y libpq-dev python3-dev
        which pg_config
    - name: Build the Docker image
      run: docker-compose build app
