name: Docker App Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install/update dependencies dependency
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y libpq-dev python3-dev build-essential postgresql-server-dev-all
        which pg_config
        echo $PATH$
    - name: Build the Docker image
      run: docker-compose build app
